### PR TITLE
HDUList importer/selector

### PR DESCRIPTION
**Pull request by astrofrog**
@ChrisBeaumont - work in progress, but thought I should let you I have been working on this.

screen shot 2015-03-26 at 4 10 29 pm

Remaining to-dos:
- [ ] set widget title
- [ ] provide a 1-line instruction at the top
- [ ] decide if it should be an importer, data factory, disambiguator, etc.
- [ ] adjust so that it returns the right thing depending on how it's registered as a plugin

### CODE REVIEW

**Comment by ChrisBeaumont** [comment]
I also might want control over whether I import all HDUs as separate Data objects, Components in a single data object, or something in between. Likewise (though less important) maybe I want to rename the HDU labels when loading.

**Comment by astrofrog** [comment]
Ok, I'll have a think about how to encode that. For HDUs to be components of the same data, would the shapes have to match?

**Comment by ChrisBeaumont** [comment]
>  For HDUs to be components of the same data, would the shapes have to match?

Yes. There are cases where that's true (for example, JCMT NDF files converted to fits have one HDU for the data, one for the variance mask, one for exposure time, etc, which are pixel-aligned). 

One idea I had:
image

**Comment by astrofrog** [comment]
Ah right, I see what you are thinking. There could then be a 'new data' button and an 'add to dataset' button for each HDU (or of course, we can have drag and drop, but to keep it simple I think I know how we can do it just with buttons).

Nice use of hand drawing :)

**Comment by astrofrog** [comment]
Also the data names and component names on the right could be editable

**Comment by astrofrog** [comment]
Hmm, thinking about this more, this could be generalized so that the left could show multiple files so the left pane would look like:

```
File: blah.fits
    HDU1: ... (shape, etc.)
    HDU2: ...
File: another.hdf5
    Data1: ...
    Data2: ...
etc.
```

and then the right would be as you show - this could allow creating new datasets, setting components, etc. and would go well beyond just an HDUList importer. One could imagine having (as shown above) in the left a FITS file, an HDF5 file, etc. The user can just customize how the data objects are build and rename components etc. as needed. Maybe then we don't need an HDUList specific GUI but more a GUI for doing this kind of work.

This would allow merging say 4 FITS files into a single dataset.

**Comment by astrofrog** [comment]
Since that approach is quite different, I'll open up another PR for experimenting. I think we can use a `QTreeWidget` on both sides and then allow drag-and-drop and renaming.

**Comment by astrofrog** [comment]
@ChrisBeaumont - what about something along these lines with drag and drop from left to right, and ability to rename on the right?

screen shot 2015-03-26 at 7 10 32 pm

(I know this is ugly, but just a mock-up!)

**Comment by ChrisBeaumont** [comment]
Looks promising!

**Comment by astrofrog** [comment]
Hmm, this requires more thought:
- Individual HDUs might contain multiple components (e.g. world coordinates) so I'd have to show those in the list on the left.
- In the case of tables, things shown on the right would not necessarily be components under each dataset (because if there are 100 columns that will be a lot of things to scroll over in the right) but groups of columns. But it makes renaming component names hard.

So I _think_ that it should be do-able but the renaming part is going to be trickier for components.

**Comment by astrofrog** [comment]
@ChrisBeaumont - it seems that we are in any case in agreement with the importer part existing, so how about I try and finalize this PR and then we can already merge in the ability to register importers, and the importers are allowed to return ``Data``. Later, we can then settle on a framework for dealing with disambiguation, etc. and start allowing importers to not return ``Data``. Does that sound like a reasonable way forward? Basically if we start off restrictive (importers have to return ``Data``) then any change in future should be backward-compatible?

**Comment by astrofrog** [comment]
(commented on wrong PR)

**Comment by astrofrog** [comment]
I'm going to close this as this was just experimental and there are many other higher priorities now in the glue world :)

**Pull request closed without merging**
