### PR TITLE
Initial version of webcam importer, with preview display

### PR DESCRIPTION
**Pull request by astrofrog**
This is a more complete version of a webcam widget including a preview screen, ability to capture or try again.

screen shot 2015-03-25 at 10 15 04 pm

Todos:
- [x] Ability to use it as an actual plugin (requires new registry in glue)
- [x] Don't allow ok until capture is frozen
- [ ] <s>Add instructions above</s> (not needed, pretty simple!)

### CODE REVIEW

**Comment by astrofrog** [comment]
Capture and Try Again could be made into the same button

**Comment by astrofrog** [comment]
This is also now ready

**Comment by astrofrog** [comment]
@ChrisBeaumont - I'll leave this open for a few days in case you have any suggestions on separating the GUI and non-GUI code further for this plugin too.

**Comment by ChrisBeaumont** [comment]
Looks good to me!

**Pull request merged**
